# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# THIS FILE IS AUTO-GENERATED BY THE web-server/bin/gen-dockerfiles BINARY!
# DO NOT EDIT THIS FILE MANUALLY!
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FROM debian:stretch-slim

<?php if ($debug): ?>
ENTRYPOINT ["/usr/local/sbin/nginx", "-g", "error_log /var/log/nginx/error.log debug;"]
<?php else: ?>
ENTRYPOINT ["/usr/local/sbin/nginx"]
<?php endif ?>
EXPOSE 443
EXPOSE 80
STOPSIGNAL SIGTERM
WORKDIR /srv/www

ENV DEBIAN_FRONTEND="teletype" LANG="C.UTF-8"

COPY resources/vendor-keys.pub /usr/local/src/vendor-keys.pub

RUN set -exu;\
#
# ------------------------------------------------------------------------------ Config
#
readonly NGINX_VERSION=<?= $config['nginx']['version'] ?>;\
readonly NGINX_DIGEST=<?= $config['nginx']['digest'] ?>;\
readonly OPENSSL_VERSION=<?= $config['openssl']['version'] ?>;\
readonly OPENSSL_DIGEST=<?= $config['openssl']['digest'] ?>;\
readonly PCRE_VERSION=<?= $config['pcre']['version'] ?>;\
readonly PCRE_DIGEST=<?= $config['pcre']['digest'] ?>;\
readonly ZLIB_VERSION=<?= $config['zlib']['version'] ?>;\
readonly ZLIB_DIGEST=<?= $config['zlib']['digest'] ?>;\
readonly BUILD_DEPS='build-essential ca-certificates curl gnupg';\
#
# ------------------------------------------------------------------------------
#
info() { printf '\n\033[33m%s\033[0m\n\n' "$1"; };\
apt_update() { apt-get update -qq; };\
apt_install() { apt-get install -qqy --auto-remove --no-install-recommends --no-install-suggests $*; };\
#
mkdir -p /etc/dpkg/dpkg.conf.d;\
touch /etc/dpkg/dpkg.conf.d/01_nodoc;\
for e in 'doc-base doc groff info linda lintian man';\
	do echo "path-exclude /usr/share/${e}/*" >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
done;\
#
cd /usr/local/src;\
info 'installing build dependencies';\
apt_update;\
apt_install ${BUILD_DEPS};\
#
info 'importing vendor GPG keys';\
gpg --import vendor-keys.pub;\
#
info 'downloading dependencies';\
echo '#!/bin/sh' > dl;\
echo 'curl -sLSo $2.tar.gz $1/$2-$3.tar.gz' >> dl;\
echo 'echo "$4 *$2.tar.gz" | sha256sum -c -' >> dl;\
echo 'curl -sLSo $2.tar.gz.$5 $1/$2-$3.tar.gz.$5' >> dl;\
echo 'gpg --batch --verify $2.tar.gz.$5 $2.tar.gz' >> dl;\
echo 'tar -xzf $2.tar.gz' >> dl;\
echo 'mv $2-$3 $2' >> dl;\
chmod +x dl;\
#
./dl 'https://nginx.org/download' 'nginx' "${NGINX_VERSION}" "${NGINX_DIGEST}" 'asc';\
./dl 'https://www.openssl.org/source' 'openssl' "${OPENSSL_VERSION}" "${OPENSSL_DIGEST}" 'asc';\
./dl 'ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre' 'pcre' "${PCRE_VERSION}" "${PCRE_DIGEST}" 'sig';\
./dl 'http://zlib.net' 'zlib' "${ZLIB_VERSION}" "${ZLIB_DIGEST}" 'asc';\
#
info "building and installing nginx ${NGINX_VERSION}";\
cd nginx; \
adduser --system --group --disabled-password --disabled-login --no-create-home nginx;\
./configure \
#
--user=nginx \
--group=nginx \
#
--prefix=/usr/local \
--sbin-path=/usr/local/sbin \
#
--with-cc-opt='-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpic -fpie -O2 -pipe' \
--with-ld-opt='-pie -s -Wl,-O1 -Wl,--hash-style,gnu -Wl,-z,relro -Wl,-z,now' \
#
--conf-path=/usr/local/etc/nginx/main.ngx \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
#
--http-client-body-temp-path=/var/cache/nginx/client-bodies \
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi \
#
<?php if ($debug): ?>
--with-debug \
<?php endif ?>
--with-http_ssl_module \
--with-http_v2_module \
--with-openssl-opt='-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpic -fpie -pipe enable-ec_nistp_64_gcc_128 no-comp -no-deprecated no-dso no-dtls no-dynamic-engine no-engine no-err no-heartbeats no-idea no-md2 no-md4 no-mdc2 no-rc2 no-rc4 no-rc5 no-static-engine' \
--with-openssl=../openssl \
--with-pcre=../pcre \
--with-pcre-jit \
--with-pcre-opt='-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpic -fpie -O2 -pipe' \
--with-zlib=../zlib \
--with-zlib-opt='-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpic -fpie -O2 -pipe' \
#
--without-http_access_module \
--without-http_auth_basic_module \
--without-http_autoindex_module \
--without-http_empty_gif_module \
--without-http_geo_module \
--without-http_memcached_module \
--without-http_proxy_module \
--without-http_referer_module \
--without-http_scgi_module \
--without-http_split_clients_module \
--without-http_ssi_module \
--without-http_upstream_ip_hash_module \
--without-http_userid_module \
--without-http_uwsgi_module;\
make -sj `nproc`;\
make install;\
strip --strip-all /usr/local/sbin/nginx;\
mkdir -p /var/cache/nginx/client-bodies /var/cache/nginx/fastcgi;\
#
mkdir -p /var/log/nginx;\
ln -sf /dev/stdout /var/log/nginx/access.log;\
ln -sf /dev/stderr /var/log/nginx/error.log;\
#
info 'cleanup';\
apt-get purge -q -y --auto-remove ${BUILD_DEPS};\
apt-get clean -q -y;\
rm -rf \
/etc/dpkg/dpkg.conf.d/ \
/root/.gnupg/ \
/tmp/* \
/usr/local/etc/nginx/ \
/usr/local/src/ \
/usr/share/doc-base/ \
/usr/share/doc/ \
/usr/share/groff/ \
/usr/share/info/ \
/usr/share/linda/ \
/usr/share/lintian/ \
/usr/share/man/ \
/var/lib/apt/lists/* \
/var/tmp/*;\
#
printf '\n\033[32mfinished\033[0m\n\n';\
nginx -V
