version: '3.1'

services:
  web-server:
    build:
      context: ../../web-server
      dockerfile: Dockerfile.web-server
    domainname: api.fleshgrinder.docker
    hostname: web-server
    image: fleshgrinder/web-server-prod:latest
    links:
      - web-service
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../../web-server/config/nginx:/usr/local/etc/nginx:ro'
      - '../../web-service/src/webapp:/srv/www/web-service/src/webapp:ro'

  web-service:
    build:
      context: ../../web-service
      dockerfile: Dockerfile.web-service
    domainname: api.fleshgrinder.docker
    env:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - PHP_ZEND_ASSERTIONS=0
    hostname: web-service
    image: fleshgrinder/web-service-prod:latest
    volumes:
      - '../../web-service/config/php:/usr/local/etc/php:ro'
      - '../../web-service/src/main/php:/srv/www/web-service/src/main/php:ro'
      - '../../web-service/src/webapp:/srv/www/web-service/src/webapp:ro'
