version: 2

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code
      - build_web_service_test_image:
          filters: {branches: {only: [master]}}
          requires: [checkout_code]
      - test_web_service:
          requires: [checkout_code, build_web_service_test_image]
      - build_web_service_image:
          requires: [test_web_service]
      - generate_web_server_dockerfiles:
          requires: [test_web_service]
      - build_web_server_image:
          requires: [generate_web_server_dockerfiles]

jobs:
  checkout_code:
    docker: [{image: fleshgrinder/alpine-git-tar}]
    working_directory: /src
    steps:
      - checkout
      - persist_to_workspace: {root: /src, paths: [.]}

  build_web_service_test_image:
    docker: [{image: fleshgrinder/docker-buildpack}]
    working_directory: /src/web-service
    steps:
      - attach_workspace: {at: /src}
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-web-service-test-{{ checksum "Dockerfile.web-service-test" }}
            - v1-web-service-test
          paths: [/cache/docker/web-service-test.tar]
      - run:
          name: Load Docker Cache
          command: |
            set +o pipefail
            docker load -i /cache/docker/web-service-test.tar | true
            docker images
      - run:
          name: Build Web Service Test
          command: |
            COMMIT_RANGE=$(echo "${CIRCLE_COMPARE_URL}" | sed 's:^.*/compare/::g')
            if git diff "${COMMIT_RANGE}" --name-status | grep Dockerfile.web-service-test
              then make web-service-test
              else touch /skip
            fi
      - run:
          name: Save Docker Cache
          command: |
            if [ -f /skip ]
            then
              echo skipping
            else
              mkdir -p /cache/docker
              docker save -o /cache/docker/web-service-test.tar fleshgrinder/web-service-test
            fi
      - save_cache:
          key: v1-web-service-test-{{ checksum "Dockerfile.web-service-test" }}
          paths: [/cache/docker/web-service-test.tar]
      - run:
          name: Push Docker Image
          command: |
            if [ -f /skip ]
            then
              echo skipping
            else
              docker login -u fleshgrinder -p "${DOCKER_PASS}"
              docker push fleshgrinder/web-service-test:latest
            fi

  test_web_service:
    docker: [{image: fleshgrinder/web-service-test}]
    working_directory: /src/web-service
    steps:
      - attach_workspace: {at: /src}
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            - v1-composer
          paths:
            - /root/.composer
            - /src/web-service/vendor
      - run:
          name: Install Dependencies
          command: composer install --no-progress --no-suggest
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - /root/.composer
            - /src/web-service/vendor
      - run:
          name: Execute Tests
          command: composer test
      - store_artifacts: {path: code-coverage}

  build_web_service_image:
    docker: [{image: fleshgrinder/docker-buildpack}]
    working_directory: /src/web-service
    steps:
      - attach_workspace: {at: /src}
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-web-service-{{ checksum "Dockerfile.web-service" }}
            - v1-web-service
          paths: [/cache/docker/web-service.tar]
      - run:
          name: Load Docker Cache
          command: |
            set +o pipefail
            docker load -i /cache/docker/web-service.tar | true
            docker images
      - run:
          name: Build Web Service Test
          command: make web-service
      - run:
          name: Save Docker Cache
          command: |
            mkdir -p /cache/docker
            docker save -o /cache/docker/web-service.tar fleshgrinder/web-service
      - save_cache:
          key: v1-web-service-{{ checksum "Dockerfile.web-service" }}
          paths: [/cache/docker/web-service.tar]
      - run:
          name: Push Docker Image
          command: |
            docker login -u fleshgrinder -p "${DOCKER_PASS}"
            docker push fleshgrinder/web-service:latest

  generate_web_server_dockerfiles:
    docker: [{image: fleshgrinder/web-service-test}]
    working_directory: /src/web-server
    steps:
      - attach_workspace: {at: /src}
      - run:
          name: Generate Dockerfiles
          command: php bin/gen-dockerfiles
      - persist_to_workspace: {root: /src, paths: [web-server/Dockerfile.web-server]}

  build_web_server_image:
    docker: [{image: fleshgrinder/docker-buildpack}]
    working_directory: /src/web-server
    steps:
      - attach_workspace: {at: /src}
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-web-server-{{ checksum "Dockerfile.web-server" }}
            - v1-web-server
          paths: [/cache/docker/web-server.tar]
      - run:
          name: Load Docker Cache
          command: |
            set +o pipefail
            docker load -i /cache/docker/web-server.tar | true
            docker images
      - run:
          name: Build Web Service Test
          command: make web-server
      - run:
          name: Save Docker Cache
          command: |
            mkdir -p /cache/docker
            docker save -o /cache/docker/web-server.tar fleshgrinder/web-server
      - save_cache:
          key: v1-web-server-{{ checksum "Dockerfile.web-server" }}
          paths: [/cache/docker/web-server.tar]
      - run:
          name: Push Docker Image
          command: |
            docker login -u fleshgrinder -p "${DOCKER_PASS}"
            docker push fleshgrinder/web-server:latest
