version: 2

cwd: &cwd
  working_directory: /usr/local/src

alpine_git: &alpine_git
  docker:
    - image: alpine/git
  <<: *cwd

docker_buildpack: &docker_buildpack
  docker:
    - image: fleshgrinder/docker-buildpack:17.06.0-ce
  <<: *cwd

jobs:
  checkout:
    <<: *alpine_git
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_web_server:
    <<: *docker_buildpack
    steps:
      - attach_workspace:
          at: /usr/local/src
      - setup_remote_docker
      - run:
          name: Build Web Server Container
          command: make server
  build_web_service:
    <<: *_buildpack
    steps:
      - attach_workspace:
          at: /usr/local/src
      - setup_remote_docker
      - run:
          name: Build Web Service Container
          command: make service

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - build_web_server:
          requires:
            - checkout
      - build_web_service:
          requires:
            - checkout
