version: 2
jobs:
  build:
    working_directory: /usr/local/src
    docker:
      - image: buildpack-deps:xenial
    steps:
      - checkout
      - ls -la
  hello_world:
    steps:
      - run: ls -la
      - run: echo 'Hello, World!'

workflows:
  version: 2
  pipelines:
    jobs:
      - build
      - hello_world:
          requires:
            - build
