version: 2

defaults: &defaults
  docker:
    - image: buildpack-deps:xenial
  working_directory: /usr/local/src

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  hello_world:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /usr/local/src
      - run: ls -la
      - run: echo 'Hello, World!'

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - hello_world:
          requires:
            - checkout
