admin:
   ip: 0.0.0.0
   port: 9990

# Should be consul in this case later on
#namers:
#  - kind: io.l5d.fs
#    rootDir: /#/srv/www/web-service/src/webapp
#    rootDir: disco

routers:
- protocol: h2
  experimental: true
  label: grpc
  servers:
  - port: 4140
# Announcer section later on used for service discovery (consul)
#    announce:
#    	kind: /#/io.l5d.serversets
#    	zkAddrs:
#    	  - host: x.x.x.x
#    		port: xxxx
#    	pathPrefix: /x
#    	prefix: /
  identifier:
    kind: io.l5d.header.path
    segments: 2
  client:
    loadBalancer:
      kind: ewma
      maxEffort: 10
      decayTimeMs: 100
  dtab: |
    /svc => /#/io.l5d.fs
